"""initial_schema

Revision ID: 072db20cb7b3
Revises: 
Create Date: 2026-04-30 01:50:23.718568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072db20cb7b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='residencestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('billing_cycle_day BETWEEN 1 AND 31', name='ck_residences_billing_cycle_day'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_residence_id'), 'blocks', ['residence_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'residence_admin', 'finance_admin', 'resident', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='entitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('residence_id', 'email', name='uq_users_residence_email')
    )
    op.create_index(op.f('ix_users_residence_id'), 'users', ['residence_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_residence_id'), 'audit_logs', ['residence_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Enum('units', 'opening_balances', 'historical_payments', 'monthly_charges', name='importtype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'validated', 'processing', 'completed', 'failed', 'cancelled', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_rows >= 0', name='ck_import_batches_failed_rows_non_negative'),
    sa.CheckConstraint('success_rows >= 0', name='ck_import_batches_success_rows_non_negative'),
    sa.CheckConstraint('total_rows >= 0', name='ck_import_batches_total_rows_non_negative'),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_residence_id'), 'import_batches', ['residence_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=40), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('owner_phone', sa.String(length=40), nullable=True),
    sa.Column('owner_email', sa.String(length=254), nullable=True),
    sa.Column('tenant_name', sa.String(length=120), nullable=True),
    sa.Column('tenant_phone', sa.String(length=40), nullable=True),
    sa.Column('tenant_email', sa.String(length=254), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='entitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('residence_id', 'block_id', 'unit_number', name='uq_units_residence_block_number')
    )
    op.create_index(op.f('ix_units_block_id'), 'units', ['block_id'], unique=False)
    op.create_index(op.f('ix_units_residence_id'), 'units', ['residence_id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('total_charged', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('oldest_unpaid_due_date', sa.Date(), nullable=True),
    sa.Column('months_overdue', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('healthy', 'pending_verification', 'recently_overdue', 'long_overdue', 'never_paid', 'irregular', 'legacy_debtor', 'on_installment', 'under_review', name='classificationcategory'), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('last_follow_up_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('months_overdue >= 0', name='ck_account_snapshots_months_overdue_non_negative'),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('residence_id', 'unit_id', name='uq_account_snapshots_residence_unit')
    )
    op.create_index(op.f('ix_account_snapshots_residence_id'), 'account_snapshots', ['residence_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_unit_id'), 'account_snapshots', ['unit_id'], unique=False)
    op.create_table('admin_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('internal_only', 'visible_to_finance_admin', 'visible_to_resident', name='notevisibility'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notes_residence_id'), 'admin_notes', ['residence_id'], unique=False)
    op.create_index(op.f('ix_admin_notes_unit_id'), 'admin_notes', ['unit_id'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partially_paid', 'paid', 'waived', 'cancelled', 'overdue', name='chargestatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_charges_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_residence_id'), 'charges', ['residence_id'], unique=False)
    op.create_index(op.f('ix_charges_unit_id'), 'charges', ['unit_id'], unique=False)
    op.create_table('follow_up_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('follow_up_type', sa.Enum('whatsapp', 'phone_call', 'email', 'in_person', 'notice_letter', 'legal_warning', 'other', name='followuptype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'no_response', 'promised_to_pay', 'escalated', name='followupstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_records_residence_id'), 'follow_up_records', ['residence_id'], unique=False)
    op.create_index(op.f('ix_follow_up_records_unit_id'), 'follow_up_records', ['unit_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.CheckConstraint('row_number > 0', name='ck_import_errors_row_number_positive'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_batch_id'), 'import_errors', ['import_batch_id'], unique=False)
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'defaulted', 'cancelled', name='installmentplanstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('total_amount > 0', name='ck_installment_plans_total_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_plans_residence_id'), 'installment_plans', ['residence_id'], unique=False)
    op.create_index(op.f('ix_installment_plans_unit_id'), 'installment_plans', ['unit_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('payment_submitted', 'payment_verified', 'payment_rejected', 'overdue_reminder', 'installment_due', 'follow_up_due', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'whatsapp_manual', 'whatsapp_api_later', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'cancelled', name='notificationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_residence_id'), 'notifications', ['residence_id'], unique=False)
    op.create_index(op.f('ix_notifications_unit_id'), 'notifications', ['unit_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=60), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending_verification', 'verified', 'rejected', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['residence_id'], ['residences.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_residence_id'), 'payments', ['residence_id'], unique=False)
    op.create_index(op.f('ix_payments_unit_id'), 'payments', ['unit_id'], unique=False)
    op.create_table('unit_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('owner', 'tenant', 'representative', name='unituserrelationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'user_id', name='uq_unit_users_unit_user')
    )
    op.create_index(op.f('ix_unit_users_unit_id'), 'unit_users', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_users_user_id'), 'unit_users', ['user_id'], unique=False)
    op.create_table('installment_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_plan_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partially_paid', 'paid', 'missed', name='installmentschedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_due > 0', name='ck_installment_schedules_amount_due_positive'),
    sa.CheckConstraint('amount_paid >= 0', name='ck_installment_schedules_amount_paid_non_negative'),
    sa.ForeignKeyConstraint(['installment_plan_id'], ['installment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_schedules_installment_plan_id'), 'installment_schedules', ['installment_plan_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_allocated > 0', name='ck_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'charge_id', name='uq_payment_allocations_payment_charge')
    )
    op.create_index(op.f('ix_payment_allocations_charge_id'), 'payment_allocations', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('payment_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('file_size > 0', name='ck_payment_proofs_file_size_positive'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_payment_id'), 'payment_proofs', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proofs_payment_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_charge_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_installment_schedules_installment_plan_id'), table_name='installment_schedules')
    op.drop_table('installment_schedules')
    op.drop_index(op.f('ix_unit_users_user_id'), table_name='unit_users')
    op.drop_index(op.f('ix_unit_users_unit_id'), table_name='unit_users')
    op.drop_table('unit_users')
    op.drop_index(op.f('ix_payments_unit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_residence_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_unit_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_residence_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_installment_plans_unit_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_residence_id'), table_name='installment_plans')
    op.drop_table('installment_plans')
    op.drop_index(op.f('ix_import_errors_import_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_follow_up_records_unit_id'), table_name='follow_up_records')
    op.drop_index(op.f('ix_follow_up_records_residence_id'), table_name='follow_up_records')
    op.drop_table('follow_up_records')
    op.drop_index(op.f('ix_charges_unit_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_residence_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_admin_notes_unit_id'), table_name='admin_notes')
    op.drop_index(op.f('ix_admin_notes_residence_id'), table_name='admin_notes')
    op.drop_table('admin_notes')
    op.drop_index(op.f('ix_account_snapshots_unit_id'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_residence_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_units_residence_id'), table_name='units')
    op.drop_index(op.f('ix_units_block_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_import_batches_residence_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_audit_logs_residence_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_residence_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_blocks_residence_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('residences')
    # ### end Alembic commands ###
